# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f0e196f227b828ad5d840c9569875afa9524e50f7600d1548a8234d6dead2ef0a5bd0c3482e2bb888346d54415428e96e6bba3f0cf10d6e1c93fd7f0a0c2eb5

test:
  secret_key_base: 60dc00e57a4a8be900a300d40cb7b9322eab4a09d362598afa2c3eb5a6e1ba271aff1d84fd29fe969110d52327de5899569579f5882e02d1df9fc0d6f06fbf31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
